env:
  browser: true
plugins:
  - jsdoc
extends:
  - plugin:jsdoc/recommended-typescript-error
rules:
  jsdoc/tag-lines:
    - error
    - always
    - count: 0
      startLines: 1
settings:
  jsdoc:
    ignorePrivate: true
    ignoreInternal: true
