root: true
env:
  es2021: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
rules:
  camelcase:
    - error
    - properties: never
      allow:
        - __webpack_public_path__
  curly: error
  eqeqeq: error
  no-constructor-return: error
  no-unused-vars:
    - error
    - argsIgnorePattern: ^_
  prefer-const: error
  spaced-comment:
    - error
    - always
    - block:
        balanced: true
overrides:
  # TypeScript rules.
  - files:
      - '*.ts'
    parser: '@typescript-eslint/parser'
    plugins:
      - '@typescript-eslint'
    extends:
      - plugin:@typescript-eslint/recommended
    rules:
      '@typescript-eslint/no-non-null-assertion': 'off'
      '@typescript-eslint/no-unused-vars':
        - error
        - argsIgnorePattern: ^_
      # Disallow non-const enums, as they generate unnecessary code.
      # Taken from https://github.com/typescript-eslint/typescript-eslint/issues/561#issuecomment-593059472.
      no-restricted-syntax:
        - error
        - selector: 'TSEnumDeclaration:not([const=true])'
          message: Don't declare non-const enums
